### ISSUE TITLE
[Breaking change] Changing the website API style

### ISSUE THREAD

**Issue by Ilshidur** [Ilshidur/LoL-item-sets-Mac#2]
Hello.

As I am currently changing the website API, some "endpoints" won't be supported anymore once the new website is deployed. This will eventually break the app.

All API endpoints will be JSON strings.
Here are the "future broken" endpoints :
- [/?version](https://lol-item-sets-generator.org//?version) will be replaced by [/api/patch](https://lol-item-sets-generator.org//api/patch)
  - previous output : `5.16.2`
  - future output : `{"version":"6.16.2","generationDate":"2016-08-20T22:00:40.930Z"}`
- [/clicks/click.php?id=dl_sets_from_application](https://lol-item-sets-generator.org/clicks/click.php?id=dl_sets_from_application) will be replaced by [/downloads/sets-from-app](https://lol-item-sets-generator.org/downloads/sets-from-app)
  - no changes in the output file

There will also be a [/api/news](https://lol-item-sets-generator.org/api/news) endpoint containing to potential text to show in the app. Output example : `{"text":"We are sorry to announce that the ProBuilds build order will be disabled until we manage to fix the generator. Stay tuned !"}`

I made a temporarily copy of the website on (edit: **removed**) for debugging purposes ;-)

The website will be deployed right after the release of the new functional Windows and Mac apps :)

**Comment by melchor629** [comment]
Ok, I will start updating all the stuff.

Only one question, on `/api/news/` if there's nothing to show, will return something like `{"text": null}`?

**Comment by Ilshidur** [comment]
Thank you ! It will return `{"text": ''}` (empty string).
The `generationDate` field is a serialized (Javascript) `Date` type using `JSON.stringify`.

**Comment by melchor629** [comment]
With 9805a13 all changes are uploaded to the repo and the update is ready

**Comment by Ilshidur** [comment]
Wow, thanks a lot for the very fast changes !
I will now close this issue once the migration process is done.
