### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by herangel** [Ilshidur/LoL-item-sets-Mac#6]
The application don't start in mac OS 10.13.6

**Comment by melchor629** [comment]
Hi @herangel . Some questions to know what is going on. Did you install it recently or did you have it from before? Do you get any errors or simply it does not open? Do you have an item set manually installed?

Currently I have 10.14 and it opens correctly, so macOS should not be the main issue.

**Comment by Ilshidur** [comment]
The issue seems to not be related to the web API, as the website had no down time since October 16th (2 minutes).

**Comment by Ilshidur** [comment]
@herangel Are you still encountering this issue ?
In case you're not, I will take the liberty to close this thread.

**Comment by Ilshidur** [comment]
Closing this thread as no answer has been provided in the last 2 weeks. Feel free to re-open it if you wish.
